create table if not exists store_campaigns (
	store_id uuid not null references stores(id) on delete cascade,
	campaign_id text not null,
	name text not null,
	description text not null default '',
	campaign_type text not null default 'interna',
	is_active boolean not null default true,
	starts_at date null,
	ends_at date null,
	target_outcome text not null default 'compra-reserva',
	min_sale_amount numeric(14, 2) not null default 0,
	max_service_minutes integer not null default 0,
	product_codes_json jsonb not null default '[]'::jsonb,
	source_ids_json jsonb not null default '[]'::jsonb,
	reason_ids_json jsonb not null default '[]'::jsonb,
	queue_jump_only boolean not null default false,
	existing_customer_filter text not null default 'all',
	bonus_fixed numeric(14, 2) not null default 0,
	bonus_rate numeric(10, 4) not null default 0,
	sort_order integer not null default 0,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	primary key (store_id, campaign_id),
	constraint store_campaigns_type_check check (campaign_type in ('interna', 'comercial')),
	constraint store_campaigns_outcome_check check (target_outcome in ('qualquer', 'compra', 'reserva', 'nao-compra', 'compra-reserva')),
	constraint store_campaigns_existing_customer_check check (existing_customer_filter in ('all', 'yes', 'no'))
);

create index if not exists store_campaigns_store_idx
	on store_campaigns (store_id, sort_order);

insert into store_campaigns (
	store_id,
	campaign_id,
	name,
	description,
	campaign_type,
	is_active,
	starts_at,
	ends_at,
	target_outcome,
	min_sale_amount,
	max_service_minutes,
	product_codes_json,
	source_ids_json,
	reason_ids_json,
	queue_jump_only,
	existing_customer_filter,
	bonus_fixed,
	bonus_rate,
	sort_order,
	created_at,
	updated_at
)
select
	settings.store_id,
	seed.campaign_id,
	seed.name,
	seed.description,
	seed.campaign_type,
	seed.is_active,
	seed.starts_at,
	seed.ends_at,
	seed.target_outcome,
	seed.min_sale_amount,
	seed.max_service_minutes,
	seed.product_codes_json,
	seed.source_ids_json,
	seed.reason_ids_json,
	seed.queue_jump_only,
	seed.existing_customer_filter,
	seed.bonus_fixed,
	seed.bonus_rate,
	seed.sort_order,
	now(),
	now()
from store_operation_settings settings
cross join (
	values
		(
			'campanha-prata-instagram',
			'Prata Instagram',
			'Campanha comercial do grupo para prata com foco em Instagram e apoio de vitrine/site.',
			'comercial',
			true,
			null::date,
			null::date,
			'compra-reserva',
			0::numeric(14, 2),
			0,
			'["COL-PRATA-004", "BRI-PRATA-009", "PUL-PRATA-010"]'::jsonb,
			'["instagram"]'::jsonb,
			'[]'::jsonb,
			false,
			'all',
			0::numeric(14, 2),
			0::numeric(10, 4),
			0
		),
		(
			'campanha-ticket-premium',
			'Ticket premium',
			'Bonus para compra ou reserva acima de R$ 5.000.',
			'interna',
			true,
			null::date,
			null::date,
			'compra-reserva',
			5000::numeric(14, 2),
			0,
			'[]'::jsonb,
			'[]'::jsonb,
			'[]'::jsonb,
			false,
			'all',
			50::numeric(14, 2),
			0.005::numeric(10, 4),
			1
		),
		(
			'campanha-recuperacao-fora-da-vez',
			'Recuperacao fora da vez',
			'Premia atendimento fora da vez que converte cliente novo.',
			'interna',
			true,
			null::date,
			null::date,
			'compra-reserva',
			0::numeric(14, 2),
			0,
			'[]'::jsonb,
			'[]'::jsonb,
			'[]'::jsonb,
			true,
			'no',
			40::numeric(14, 2),
			0.003::numeric(10, 4),
			2
		)
) as seed(
	campaign_id,
	name,
	description,
	campaign_type,
	is_active,
	starts_at,
	ends_at,
	target_outcome,
	min_sale_amount,
	max_service_minutes,
	product_codes_json,
	source_ids_json,
	reason_ids_json,
	queue_jump_only,
	existing_customer_filter,
	bonus_fixed,
	bonus_rate,
	sort_order
)
on conflict (store_id, campaign_id) do nothing;